{
    'name': 'Force delete invoice || Posted Invoice delete force fully',
    'category': 'Accounting',
    'summary': 'Using this module you can delete invoice in posted state.',
    'description': """ Using this module you can delete invoice in posted state. """,
    'price': 7,
    'version': '16.3.2.1',
    'currency': 'EUR',
    "author" : "MAISOLUTIONSLLC",
    'sequence': 1,
    "email": 'apps@maisolutionsllc.com',
    "website":'http://maisolutionsllc.com/',
    'license': 'OPL-1',
    'depends': ['account'],
    'data': [
        'security/account.xml',
        'views/account_move_view.xml',
    ],
    "live_test_url" : "https://youtu.be/y3cAXY2vdcg",
    'demo': [],
    'test': [],
    'images': ['static/description/icon.gif'],    
    'installable': True,
    'auto_install': False,
}

